# Generated by Django 5.1.5 on 2025-03-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tailscale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesnapshot",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="The device that this snapshot is for.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="tailscale.device",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="latest_snapshot",
            field=models.ForeignKey(
                help_text="The most recent snapshot of the device.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_for_device",
                to="tailscale.devicesnapshot",
            ),
        ),
    ]
