# Generated by Django 5.2.2 on 2025-10-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tailscale", "0002_devicesnapshot_device_alter_device_latest_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicesnapshot",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, help_text="When device was last active on the tailnet.", null=True
            ),
        ),
    ]
