# Generated by Django 5.1.5 on 2025-04-03 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_default_organization(apps, schema_editor):
    """If there are existing Project, CentralServer, or TemplateVariable objects,
    create an Organization and link them to it.
    """
    org = None
    for model in ("Project", "CentralServer", "TemplateVariable"):
        model = apps.get_model("publish_mdm", model)
        if model.objects.exists():
            if not org:
                org = apps.get_model("publish_mdm", "Organization").objects.create(
                    name="Auto-created Organization", slug="auto-created-organization"
                )
            model.objects.update(organization=org)


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0009_formtemplate_template_url_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("accepted", models.BooleanField(default=False, verbose_name="accepted")),
                ("key", models.CharField(max_length=64, unique=True, verbose_name="key")),
                ("sent", models.DateTimeField(null=True, verbose_name="sent")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail address")),
                (
                    "created",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="created"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(related_name="organizations", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="centralserver",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="central_servers",
                to="publish_mdm.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="publish_mdm.organization",
            ),
        ),
        migrations.AddField(
            model_name="templatevariable",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_variables",
                to="publish_mdm.organization",
            ),
        ),
        migrations.RunPython(create_default_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="centralserver",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="central_servers",
                to="publish_mdm.organization",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="publish_mdm.organization",
            ),
        ),
        migrations.AlterField(
            model_name="templatevariable",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_variables",
                to="publish_mdm.organization",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="templatevariable",
            name="unique_template_variable_name",
        ),
        migrations.AddConstraint(
            model_name="templatevariable",
            constraint=models.UniqueConstraint(
                fields=("name", "organization"), name="unique_template_variable_name"
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="inviter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="inviter",
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="publish_mdm.organization"
            ),
        ),
    ]
