# Generated by Django 5.1.5 on 2025-05-14 15:36

import apps.infisical.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0012_project_app_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="centralserver",
            name="password",
            field=apps.infisical.fields.EncryptedCharField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="centralserver",
            name="username",
            field=apps.infisical.fields.EncryptedEmailField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="centralserver",
            name="base_url",
            field=models.URLField(max_length=1024, verbose_name="base URL"),
        ),
    ]
