# Generated by Django 5.1.5 on 2025-05-14 15:36

import apps.infisical.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0012_project_app_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="centralserver",
            name="password",
            field=apps.infisical.fields.EncryptedCharField(null=True),
        ),
        migrations.AddField(
            model_name="centralserver",
            name="username",
            field=apps.infisical.fields.EncryptedEmailField(null=True),
        ),
    ]
