# Generated by Django 5.2.2 on 2025-06-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0013_centralserver_password_centralserver_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_signup_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable a public sign-up page, where anyone can enter an email address to receive an invite.",
            ),
        ),
    ]
