# Generated by Django 5.2.12 on 2026-03-25 15:29

import os
import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_android_enterprise_accounts(apps, schema_editor):
    """Create an AndroidEnterpriseAccount for each Organization that has at least one
    Policy, using the ANDROID_ENTERPRISE_ID env var as the enterprise ID. This migrates the
    legacy global enterprise ID to per-organization accounts.

    Only runs if ANDROID_ENTERPRISE_ID is set; otherwise this is a no-op (the admin will need
    to set up each org's enterprise account through the UI instead).
    """
    android_enterprise_id = os.getenv("ANDROID_ENTERPRISE_ID", "")
    if not android_enterprise_id:
        return

    AndroidEnterpriseAccount = apps.get_model("publish_mdm", "AndroidEnterpriseAccount")
    Policy = apps.get_model("mdm", "Policy")

    org_ids = (
        Policy.all_mdms.filter(organization__isnull=False, mdm="Android Enterprise")
        .values_list("organization", flat=True)
        .order_by("organization")
        .distinct()
    )

    enterprise_name = f"enterprises/{android_enterprise_id}"
    for org_id in org_ids:
        AndroidEnterpriseAccount.objects.get_or_create(
            organization_id=org_id,
            defaults={"enterprise_name": enterprise_name},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0014_organization_public_signup_enabled"),
        ("mdm", "0009_feature_policy_editor"),
    ]

    operations = [
        migrations.CreateModel(
            name="AndroidEnterpriseAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "signup_url_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="signupUrls resource name from AMAPI, e.g. 'signupUrls/C455570ef9b12bfc'.",
                        max_length=255,
                    ),
                ),
                (
                    "signup_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Google Enterprise signup URL. Navigate here to complete enterprise creation.",
                        max_length=2048,
                    ),
                ),
                (
                    "callback_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Embedded in the callback URL to authenticate Google's redirect.",
                        unique=True,
                    ),
                ),
                (
                    "enterprise_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full AMAPI enterprise resource name, e.g. 'enterprises/LC00lvvue0'.",
                        max_length=255,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="android_enterprise",
                        to="publish_mdm.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            create_android_enterprise_accounts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
