# Generated by Django 5.2.12 on 2026-04-07 13:42

import os

import apps.infisical.fields
from django.db import migrations, models


def set_org_mdm_from_env(apps, schema_editor):
    """Set organization.mdm from ACTIVE_MDM_NAME env var for zero-downtime deployment."""
    active_mdm_name = os.environ.get("ACTIVE_MDM_NAME", "TinyMDM")
    valid_choices = {"TinyMDM", "Android Enterprise"}
    if active_mdm_name not in valid_choices:
        active_mdm_name = "TinyMDM"
    Organization = apps.get_model("publish_mdm", "Organization")
    Organization.objects.update(mdm=active_mdm_name)


class Migration(migrations.Migration):

    dependencies = [
        ("publish_mdm", "0014_organization_public_signup_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="mdm",
            field=models.CharField(
                choices=[("TinyMDM", "TinyMDM"), ("Android Enterprise", "Android Enterprise")],
                default="TinyMDM",
                help_text="The Mobile Device Management system used by this organization.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_account_id",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM account ID. Leave blank to use the server-wide env var.",
                null=True,
                verbose_name="TinyMDM account ID",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_public",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API public key. Leave blank to use the server-wide env var.",
                null=True,
                verbose_name="TinyMDM API key (public)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_secret",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API secret key. Leave blank to use the server-wide env var.",
                null=True,
                verbose_name="TinyMDM API key (secret)",
            ),
        ),
        migrations.RunPython(set_org_mdm_from_env, migrations.RunPython.noop),
    ]
