# Generated by Django 5.2.12 on 2026-04-07 13:42

import os

from django.db import migrations, models

import apps.infisical.fields


def set_org_mdm_from_policies(apps, schema_editor):
    """Seed Organization.mdm and TinyMDM credentials for all existing organizations.

    Strategy:
    - If the org has at least one policy, use the mdm value from its first policy
      (policies were previously tagged with the server-wide ACTIVE_MDM_NAME, so all
      policies in a single-MDM deployment share the same value).
    - If the org has no policies, fall back to the ACTIVE_MDM_NAME env var, then "TinyMDM".
    - If the resolved mdm is "TinyMDM", also copy the global TINYMDM_* env vars into
      the org's credential fields so that existing deployments continue working without
      manual re-configuration.
    """
    Organization = apps.get_model("publish_mdm", "Organization")
    Policy = apps.get_model("mdm", "Policy")
    valid_choices = {"TinyMDM", "Android Enterprise"}
    fallback_mdm = os.environ.get("ACTIVE_MDM_NAME", "TinyMDM")
    if fallback_mdm not in valid_choices:
        fallback_mdm = "TinyMDM"

    for org in Organization.objects.all():
        first_policy = Policy.objects.filter(organization=org).order_by("pk").first()
        if first_policy and first_policy.mdm in valid_choices:
            mdm_name = first_policy.mdm
        else:
            mdm_name = fallback_mdm

        org.mdm = mdm_name

        if mdm_name == "TinyMDM":
            # Seed env-var credentials so existing orgs keep working
            org.tinymdm_apikey_public = os.environ.get("TINYMDM_APIKEY_PUBLIC") or None
            org.tinymdm_apikey_secret = os.environ.get("TINYMDM_APIKEY_SECRET") or None
            org.tinymdm_account_id = os.environ.get("TINYMDM_ACCOUNT_ID") or None

        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0014_organization_public_signup_enabled"),
        ("mdm", "0009_feature_policy_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="mdm",
            field=models.CharField(
                choices=[("TinyMDM", "TinyMDM"), ("Android Enterprise", "Android Enterprise")],
                default="TinyMDM",
                help_text="The Mobile Device Management system used by this organization.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_account_id",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM account ID. Leave blank to use the server-wide env var.",
                null=True,
                verbose_name="TinyMDM account ID",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_public",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API public key. Leave blank to use the server-wide env var.",
                null=True,
                verbose_name="TinyMDM API key (public)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_secret",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API secret key. Leave blank to use the server-wide env var.",
                null=True,
                verbose_name="TinyMDM API key (secret)",
            ),
        ),
        migrations.RunPython(set_org_mdm_from_policies, migrations.RunPython.noop),
    ]
