# Generated by Django 5.2.12 on 2026-03-25 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish_mdm", "0014_organization_public_signup_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="AndroidEnterpriseAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "signup_url_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="signupUrls resource name from AMAPI, e.g. 'signupUrls/C455570ef9b12bfc'.",
                        max_length=255,
                    ),
                ),
                (
                    "signup_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Google Enterprise signup URL. Navigate here to complete enterprise creation.",
                        max_length=2048,
                    ),
                ),
                (
                    "callback_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Embedded in the callback URL to authenticate Google's redirect.",
                        unique=True,
                    ),
                ),
                (
                    "enterprise_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full AMAPI enterprise resource name, e.g. 'enterprises/LC00lvvue0'.",
                        max_length=255,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="android_enterprise",
                        to="publish_mdm.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
