# Generated by Django 5.2.12 on 2026-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0015_androidenterpriseaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
