# Generated by Django 5.2.12 on 2026-04-07 13:42

import os

from django.db import migrations, models

import apps.infisical.fields


def set_mdm_for_existing_orgs(apps, schema_editor):
    """Seed Organization.mdm and TinyMDM credentials for all existing organizations.

    Strategy:
    - Use the ACTIVE_MDM_NAME env var to determine the MDM for all existing orgs,
      falling back to "TinyMDM".
    - If the resolved MDM is "TinyMDM", also copy the global TINYMDM_* env vars into
      the org's credential fields so that existing deployments continue working without
      re-entering credentials.
    """
    Organization = apps.get_model("publish_mdm", "Organization")
    mdm_name = os.environ.get("ACTIVE_MDM_NAME") or "TinyMDM"

    update_fields = {"mdm": mdm_name}
    if mdm_name == "TinyMDM":
        # Seed env-var credentials so existing orgs keep working
        update_fields.update(
            tinymdm_apikey_public=os.environ.get("TINYMDM_APIKEY_PUBLIC") or None,
            tinymdm_apikey_secret=os.environ.get("TINYMDM_APIKEY_SECRET") or None,
            tinymdm_account_id=os.environ.get("TINYMDM_ACCOUNT_ID") or None,
            tinymdm_policy_id=os.environ.get("MDM_DEFAULT_POLICY") or "",
        )
    Organization.objects.update(**update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0015_androidenterpriseaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="mdm",
            field=models.CharField(
                choices=[("TinyMDM", "TinyMDM"), ("Android Enterprise", "Android Enterprise")],
                default="TinyMDM",
                help_text="The Mobile Device Management system used by this organization.",
                max_length=50,
                verbose_name="MDM",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_account_id",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM account ID.",
                null=True,
                verbose_name="TinyMDM account ID",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_public",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API public key.",
                null=True,
                verbose_name="TinyMDM API key (public)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_secret",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API secret key.",
                null=True,
                verbose_name="TinyMDM API key (secret)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_policy_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="TinyMDM policy ID.",
                max_length=255,
                verbose_name="TinyMDM policy ID",
            ),
        ),
        migrations.RunPython(set_mdm_for_existing_orgs, migrations.RunPython.noop),
    ]
