# Generated by Django 5.2.12 on 2026-04-07 13:42

import os

from django.conf import settings
from django.db import migrations, models

import apps.infisical.fields


def set_org_mdm_from_policies(apps, schema_editor):
    """Seed Organization.mdm and TinyMDM credentials for all existing organizations.

    Strategy:
    - If the org has at least one policy, use the mdm value from its first policy.
    - If the org has no policies, fall back to the ACTIVE_MDM_NAME env var, then the first
      MDM in the MDM_REGISTRY setting.
    - If the resolved mdm is "TinyMDM", also copy the global TINYMDM_* env vars into
      the org's credential fields so that existing deployments continue working without
      using env vars.
    """
    Organization = apps.get_model("publish_mdm", "Organization")
    Policy = apps.get_model("mdm", "Policy")
    fallback_mdm = os.environ.get("ACTIVE_MDM_NAME")
    if fallback_mdm not in settings.MDM_REGISTRY:
        fallback_mdm = next(iter(settings.MDM_REGISTRY))

    for org in Organization.objects.all():
        first_policy = Policy.objects.filter(organization=org).order_by("pk").first()
        if first_policy and first_policy.mdm in settings.MDM_REGISTRY:
            mdm_name = first_policy.mdm
        else:
            mdm_name = fallback_mdm

        org.mdm = mdm_name

        if mdm_name == "TinyMDM":
            # Seed env-var credentials so existing orgs keep working
            org.tinymdm_apikey_public = os.environ.get("TINYMDM_APIKEY_PUBLIC") or None
            org.tinymdm_apikey_secret = os.environ.get("TINYMDM_APIKEY_SECRET") or None
            org.tinymdm_account_id = os.environ.get("TINYMDM_ACCOUNT_ID") or None

        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0015_androidenterpriseaccount"),
        ("mdm", "0010_device_manufacturer_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="mdm",
            field=models.CharField(
                choices=[("TinyMDM", "TinyMDM"), ("Android Enterprise", "Android Enterprise")],
                default="TinyMDM",
                help_text="The Mobile Device Management system used by this organization.",
                max_length=50,
                verbose_name="MDM",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_account_id",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM account ID.",
                null=True,
                verbose_name="TinyMDM account ID",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_public",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API public key.",
                null=True,
                verbose_name="TinyMDM API key (public)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tinymdm_apikey_secret",
            field=apps.infisical.fields.EncryptedCharField(
                blank=True,
                help_text="TinyMDM manager API secret key.",
                null=True,
                verbose_name="TinyMDM API key (secret)",
            ),
        ),
        migrations.RunPython(set_org_mdm_from_policies, migrations.RunPython.noop),
    ]
