# Generated by Django 5.2.12 on 2026-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0017_feature_per_org_mdm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="mdm",
            field=models.CharField(
                choices=[("Android Enterprise", "Android Enterprise"), ("TinyMDM", "TinyMDM")],
                default="Android Enterprise",
                help_text="The Mobile Device Management system used by this organization.",
                max_length=50,
                verbose_name="MDM",
            ),
        ),
    ]
