# Generated by Django 5.2.13 on 2026-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0018_alter_organization_mdm"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="collect_admin_access_settings",
            field=models.BooleanField(
                default=False, verbose_name="Access settings from within form"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_analytics",
            field=models.BooleanField(default=False, verbose_name="Show analytics setting"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_automatic_update",
            field=models.BooleanField(default=False, verbose_name="Auto-update"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_app_theme",
            field=models.BooleanField(default=False, verbose_name="Change app theme"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_autosend",
            field=models.BooleanField(default=False, verbose_name="Change auto-send"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_constraint_behavior",
            field=models.BooleanField(default=False, verbose_name="Change constraint behaviour"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_form_metadata",
            field=models.BooleanField(default=False, verbose_name="Change form metadata"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_language",
            field=models.BooleanField(default=True, verbose_name="Allow language change"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_navigation",
            field=models.BooleanField(default=False, verbose_name="Change navigation"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_project_display",
            field=models.BooleanField(default=False, verbose_name="Change project display"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_server",
            field=models.BooleanField(default=False, verbose_name="Change server"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_default_to_finalized",
            field=models.BooleanField(
                default=False, verbose_name="Show default-to-finalized setting"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_delete_after_send",
            field=models.BooleanField(default=False, verbose_name="Delete after send"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_delete_saved",
            field=models.BooleanField(default=False, verbose_name="Delete saved forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_edit_saved",
            field=models.BooleanField(default=False, verbose_name="Edit saved forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_external_app_recording",
            field=models.BooleanField(default=False, verbose_name="External app recording"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_form_update_mode",
            field=models.BooleanField(default=False, verbose_name="Show form update mode setting"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_get_blank",
            field=models.BooleanField(default=False, verbose_name="Get blank forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_guidance_hint",
            field=models.BooleanField(default=False, verbose_name="Guidance hint"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_hide_old_form_versions",
            field=models.BooleanField(default=False, verbose_name="Hide old form versions"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_high_resolution",
            field=models.BooleanField(default=False, verbose_name="High resolution"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_image_size",
            field=models.BooleanField(default=False, verbose_name="Image size"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_instance_form_sync",
            field=models.BooleanField(default=False, verbose_name="Finalize forms on import"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_jump_to",
            field=models.BooleanField(default=False, verbose_name="Jump to"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_maps",
            field=models.BooleanField(default=False, verbose_name="Maps"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_mark_as_finalized",
            field=models.BooleanField(default=False, verbose_name="Mark as finalized"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_moving_backwards",
            field=models.BooleanField(default=True, verbose_name="Allow backward navigation"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_periodic_form_updates_check",
            field=models.BooleanField(default=False, verbose_name="Show check frequency setting"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_qr_code_scanner",
            field=models.BooleanField(default=False, verbose_name="QR code scanner"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_save_as",
            field=models.BooleanField(default=False, verbose_name="Name this form"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_save_mid",
            field=models.BooleanField(default=False, verbose_name="Save form"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_send_finalized",
            field=models.BooleanField(default=False, verbose_name="Send finalized forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_view_sent",
            field=models.BooleanField(default=False, verbose_name="View sent forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_analytics",
            field=models.BooleanField(default=True, verbose_name="Analytics"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_autosend",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("wifi_only", "Wi-Fi only"),
                    ("cellular_only", "Cellular only"),
                    ("wifi_and_cellular", "Wi-Fi and cellular"),
                ],
                default="wifi_and_cellular",
                max_length=30,
                verbose_name="Auto-send",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_default_completed",
            field=models.BooleanField(default=True, verbose_name="Default to finalized"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_delete_send",
            field=models.BooleanField(default=False, verbose_name="Delete after send"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_font_size",
            field=models.CharField(
                choices=[("13", "13"), ("17", "17"), ("21", "21"), ("25", "25"), ("29", "29")],
                default="25",
                max_length=5,
                verbose_name="Font size",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_form_update_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("previously_downloaded", "Previously downloaded"),
                    ("match_exactly", "Match exactly"),
                ],
                default="match_exactly",
                max_length=30,
                verbose_name="Form update mode",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_periodic_form_updates_check",
            field=models.CharField(
                choices=[
                    ("every_fifteen_minutes", "Every 15 minutes"),
                    ("every_one_hour", "Every hour"),
                    ("every_six_hours", "Every 6 hours"),
                    ("every_24_hours", "Every 24 hours"),
                ],
                default="every_one_hour",
                max_length=30,
                verbose_name="Form update check frequency",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_project_color",
            field=models.CharField(
                blank=True,
                default="#6ec1e4",
                help_text="Hex colour shown for this project in ODK Collect.",
                max_length=50,
                verbose_name="Project colour",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_project_icon",
            field=models.CharField(
                blank=True,
                default="🇱🇾",
                help_text="Emoji icon shown for this project in ODK Collect.",
                max_length=10,
                verbose_name="Project icon",
            ),
        ),
    ]
