# Generated by Django 5.2.13 on 2026-05-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish_mdm", "0018_alter_organization_mdm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="app_language",
            new_name="collect_general_app_language",
        ),
        migrations.AlterField(
            model_name="project",
            name="collect_general_app_language",
            field=models.CharField(
                choices=[
                    ("af", "af"),
                    ("am", "am"),
                    ("ar", "ar"),
                    ("bg", "bg"),
                    ("bn", "bn"),
                    ("ca", "ca"),
                    ("cs", "cs"),
                    ("da", "da"),
                    ("de", "de"),
                    ("en", "en"),
                    ("es", "es"),
                    ("et", "et"),
                    ("fa", "fa"),
                    ("fi", "fi"),
                    ("fr", "fr"),
                    ("hi", "hi"),
                    ("in", "in"),
                    ("it", "it"),
                    ("ja", "ja"),
                    ("ka", "ka"),
                    ("km", "km"),
                    ("ln", "ln"),
                    ("lo_LA", "lo_LA"),
                    ("lt", "lt"),
                    ("mg", "mg"),
                    ("ml", "ml"),
                    ("mr", "mr"),
                    ("ms", "ms"),
                    ("my", "my"),
                    ("ne_NP", "ne_NP"),
                    ("nl", "nl"),
                    ("no", "no"),
                    ("pl", "pl"),
                    ("ps", "ps"),
                    ("pt", "pt"),
                    ("ro", "ro"),
                    ("ru", "ru"),
                    ("rw", "rw"),
                    ("si", "si"),
                    ("sl", "sl"),
                    ("so", "so"),
                    ("sq", "sq"),
                    ("sr", "sr"),
                    ("sv_SE", "sv_SE"),
                    ("sw", "sw"),
                    ("sw_KE", "sw_KE"),
                    ("te", "te"),
                    ("th_TH", "th_TH"),
                    ("ti", "ti"),
                    ("tl", "tl"),
                    ("tr", "tr"),
                    ("uk", "uk"),
                    ("ur", "ur"),
                    ("ur_PK", "ur_PK"),
                    ("vi", "vi"),
                    ("zh", "zh"),
                    ("zu", "zu"),
                ],
                default="en",
                help_text="Language used in the ODK Collect UI.",
                max_length=10,
                verbose_name="App language",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_access_settings",
            field=models.BooleanField(
                default=False, verbose_name="Access settings from within form"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_analytics",
            field=models.BooleanField(default=False, verbose_name="Show analytics setting"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_automatic_update",
            field=models.BooleanField(default=False, verbose_name="Auto-update"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_app_language",
            field=models.BooleanField(default=False, verbose_name="Change app language"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_app_theme",
            field=models.BooleanField(default=False, verbose_name="Change app theme"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_autosend",
            field=models.BooleanField(default=False, verbose_name="Change auto-send"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_constraint_behavior",
            field=models.BooleanField(default=False, verbose_name="Change constraint behaviour"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_font_size",
            field=models.BooleanField(default=False, verbose_name="Change font size"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_form_metadata",
            field=models.BooleanField(default=False, verbose_name="Change form metadata"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_language",
            field=models.BooleanField(default=True, verbose_name="Allow language change"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_navigation",
            field=models.BooleanField(default=False, verbose_name="Change navigation"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_project_display",
            field=models.BooleanField(default=False, verbose_name="Change project display"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_change_server",
            field=models.BooleanField(default=False, verbose_name="Change server"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_default_to_finalized",
            field=models.BooleanField(
                default=False, verbose_name="Show default-to-finalized setting"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_delete_after_send",
            field=models.BooleanField(default=False, verbose_name="Delete after send"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_delete_saved",
            field=models.BooleanField(default=False, verbose_name="Delete saved forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_edit_saved",
            field=models.BooleanField(default=False, verbose_name="Edit saved forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_external_app_recording",
            field=models.BooleanField(default=False, verbose_name="External app recording"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_form_update_mode",
            field=models.BooleanField(default=False, verbose_name="Show form update mode setting"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_get_blank",
            field=models.BooleanField(default=False, verbose_name="Get blank forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_guidance_hint",
            field=models.BooleanField(default=False, verbose_name="Guidance hint"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_hide_old_form_versions",
            field=models.BooleanField(default=False, verbose_name="Hide old form versions"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_high_resolution",
            field=models.BooleanField(default=False, verbose_name="High resolution"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_image_size",
            field=models.BooleanField(default=False, verbose_name="Image size"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_instance_form_sync",
            field=models.BooleanField(default=False, verbose_name="Finalize forms on import"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_jump_to",
            field=models.BooleanField(default=False, verbose_name="Jump to"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_maps",
            field=models.BooleanField(default=False, verbose_name="Maps"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_mark_as_finalized",
            field=models.BooleanField(default=False, verbose_name="Mark as finalized"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_moving_backwards",
            field=models.BooleanField(default=True, verbose_name="Allow backward navigation"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_periodic_form_updates_check",
            field=models.BooleanField(default=False, verbose_name="Show check frequency setting"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_qr_code_scanner",
            field=models.BooleanField(default=False, verbose_name="QR code scanner"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_save_as",
            field=models.BooleanField(default=False, verbose_name="Name this form"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_save_mid",
            field=models.BooleanField(default=False, verbose_name="Save form"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_send_finalized",
            field=models.BooleanField(default=False, verbose_name="Send finalized forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_admin_view_sent",
            field=models.BooleanField(default=False, verbose_name="View sent forms"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_analytics",
            field=models.BooleanField(default=True, verbose_name="Analytics"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_app_theme",
            field=models.CharField(
                blank=True,
                choices=[("light_theme", "Light"), ("dark_theme", "Dark")],
                default="",
                max_length=20,
                verbose_name="App theme",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_automatic_update",
            field=models.BooleanField(default=False, verbose_name="Automatic update"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_autosend",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("wifi_only", "Wi-Fi only"),
                    ("cellular_only", "Cellular only"),
                    ("wifi_and_cellular", "Wi-Fi and cellular"),
                ],
                default="wifi_and_cellular",
                max_length=30,
                verbose_name="Auto-send",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_basemap_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google"),
                    ("mapbox", "Mapbox"),
                    ("osm", "OpenStreetMap"),
                    ("usgs", "USGS"),
                    ("stamen", "Stamen"),
                    ("carto", "Carto"),
                ],
                default="",
                max_length=20,
                verbose_name="Basemap source",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_carto_map_style",
            field=models.CharField(
                blank=True,
                choices=[("positron", "Positron"), ("dark_matter", "Dark matter")],
                default="",
                max_length=20,
                verbose_name="Carto map style",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_constraint_behavior",
            field=models.CharField(
                blank=True,
                choices=[("on_swipe", "On swipe"), ("on_finalize", "On finalize")],
                default="",
                max_length=20,
                verbose_name="Constraint behaviour",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_default_completed",
            field=models.BooleanField(default=True, verbose_name="Default to finalized"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_delete_send",
            field=models.BooleanField(default=False, verbose_name="Delete after send"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_external_app_recording",
            field=models.BooleanField(
                default=True, verbose_name="Allow external app to record audio"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_font_size",
            field=models.CharField(
                choices=[("13", "13"), ("17", "17"), ("21", "21"), ("25", "25"), ("29", "29")],
                default="25",
                max_length=5,
                verbose_name="Font size",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_form_update_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("previously_downloaded", "Previously downloaded"),
                    ("match_exactly", "Match exactly"),
                ],
                default="match_exactly",
                max_length=30,
                verbose_name="Form update mode",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_formlist_url",
            field=models.CharField(
                blank=True, default="", max_length=2048, verbose_name="Form list URL"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_google_map_style",
            field=models.CharField(
                blank=True,
                choices=[("1", "Normal"), ("2", "Satellite"), ("3", "Terrain"), ("4", "Hybrid")],
                default="",
                max_length=5,
                verbose_name="Google map style",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_google_sheets_url",
            field=models.CharField(
                blank=True, default="", max_length=2048, verbose_name="Google Sheets URL"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_guidance_hint",
            field=models.CharField(
                blank=True,
                choices=[("no", "Never"), ("yes", "Always"), ("yes_collapsed", "Collapsed")],
                default="",
                max_length=20,
                verbose_name="Guidance for questions",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_hide_old_form_versions",
            field=models.BooleanField(default=False, verbose_name="Hide old form versions"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_high_resolution",
            field=models.BooleanField(default=False, verbose_name="High-resolution video"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_image_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("original", "Original"),
                    ("large", "Large"),
                    ("medium", "Medium"),
                    ("small", "Small"),
                    ("very_small", "Very small"),
                ],
                default="",
                max_length=20,
                verbose_name="Image size",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_instance_sync",
            field=models.BooleanField(default=False, verbose_name="Finalize forms on import"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_mapbox_map_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mapbox://styles/mapbox/light-v10", "Light"),
                    ("mapbox://styles/mapbox/dark-v10", "Dark"),
                    ("mapbox://styles/mapbox/satellite-v9", "Satellite"),
                    ("mapbox://styles/mapbox/satellite-streets-v11", "Satellite streets"),
                    ("mapbox://styles/mapbox/outdoors-v11", "Outdoors"),
                ],
                default="",
                max_length=100,
                verbose_name="Mapbox map style",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_metadata_email",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Email address (metadata)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_metadata_phonenumber",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Phone number (metadata)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_metadata_username",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Username (metadata)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_navigation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("swipe", "Swipe"),
                    ("buttons", "Buttons"),
                    ("swipe_buttons", "Swipe and buttons"),
                ],
                default="",
                max_length=20,
                verbose_name="Navigation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_password",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Password"),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_periodic_form_updates_check",
            field=models.CharField(
                choices=[
                    ("every_fifteen_minutes", "Every 15 minutes"),
                    ("every_one_hour", "Every hour"),
                    ("every_six_hours", "Every 6 hours"),
                    ("every_24_hours", "Every 24 hours"),
                ],
                default="every_one_hour",
                max_length=30,
                verbose_name="Form update check frequency",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_protocol",
            field=models.CharField(
                blank=True,
                choices=[("odk_default", "ODK default"), ("google_sheets", "Google Sheets")],
                default="",
                max_length=20,
                verbose_name="Protocol",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_reference_layer",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Absolute path to an MBTiles file.",
                max_length=2048,
                verbose_name="Reference layer",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_submission_url",
            field=models.CharField(
                blank=True, default="", max_length=2048, verbose_name="Submission URL"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_general_usgs_map_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("topographic", "Topographic"),
                    ("hybrid", "Hybrid"),
                    ("satellite", "Satellite"),
                ],
                default="",
                max_length=20,
                verbose_name="USGS map style",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_project_color",
            field=models.CharField(
                blank=True,
                default="#6ec1e4",
                help_text="Hex colour shown for this project in ODK Collect.",
                max_length=50,
                verbose_name="Project colour",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="collect_project_icon",
            field=models.CharField(
                blank=True,
                default="🇱🇾",
                help_text="Emoji icon shown for this project in ODK Collect.",
                max_length=10,
                verbose_name="Project icon",
            ),
        ),
    ]
