# Generated by Django 5.1.5 on 2025-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="central_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The ID of this app user in ODK Central.",
                null=True,
                verbose_name="app user ID",
            ),
        ),
    ]
