# Generated by Django 5.1.5 on 2025-02-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0002_alter_appuser_central_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatevariable",
            name="transform",
            field=models.CharField(blank=True, choices=[("sha256-digest", "SHA256_DIGEST")]),
        ),
    ]
