# Generated by Django 5.1.5 on 2025-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0003_alter_appuser_name"),
        ("odk_publish", "0003_templatevariable_transform"),
    ]

    operations = []
