# Generated by Django 5.1.5 on 2025-03-05 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0003_projectattachment"),
        ("odk_publish", "0004_merge_20250305_0935"),
    ]

    operations = []
