# Generated by Django 5.1.5 on 2025-03-11 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0005_appuser_qr_code_data"),
        ("odk_publish", "0005_merge_0003_projectattachment_0004_merge_20250305_0935"),
    ]

    operations = []
