# Generated by Django 5.1.5 on 2025-03-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odk_publish", "0007_add_admin_pw_template_variable"),
        ("odk_publish", "0007_alter_appuser_name"),
    ]

    operations = []
