# Generated by Django 5.1.5 on 2025-03-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0007_alter_appuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="template_variables",
            field=models.ManyToManyField(
                blank=True,
                help_text="Variables selected here will be set for each app user.",
                related_name="projects",
                to="odk_publish.templatevariable",
                verbose_name="App user template variables",
            ),
        ),
        migrations.CreateModel(
            name="ProjectTemplateVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Optional",
                        max_length=1024,
                        verbose_name="Project-wide value",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_template_variables",
                        to="odk_publish.project",
                    ),
                ),
                (
                    "template_variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_through",
                        to="odk_publish.templatevariable",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "template_variable"),
                        name="unique_project_template_variable",
                    )
                ],
            },
        ),
    ]
