# Generated by Django 5.1.5 on 2025-03-18 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0007_alter_appuser_name"),
        ("odk_publish", "0007_formtemplate_template_url_user"),
    ]

    operations = []
