# Generated by Django 5.1.5 on 2025-03-19 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0006_alter_project_template_variables_and_more"),
        ("odk_publish", "0008_formtemplate_template_url_user_and_more"),
    ]

    operations = []
