# Generated by Django 5.1.5 on 2025-03-20 14:46

from django.db import migrations


def create_admin_pw_variable(apps, schema_editor):
    TemplateVariable = apps.get_model("odk_publish", "TemplateVariable")
    TemplateVariable.objects.get_or_create(name="admin_pw")


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0009_formtemplate_template_url_user_and_more"),
    ]

    operations = [
        migrations.RunPython(create_admin_pw_variable, reverse_code=migrations.RunPython.noop),
    ]
