# Generated by Django 5.1.5 on 2025-03-20 14:46

from django.db import migrations


def create_admin_pw_variable(apps, schema_editor):
    Project = apps.get_model("odk_publish", "Project")
    TemplateVariable = apps.get_model("odk_publish", "TemplateVariable")

    for project in Project.objects.all():
        TemplateVariable.objects.get_or_create(
            name="admin_pw",
            project=project,
            defaults={"value": ""},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0009_formtemplate_template_url_user_and_more"),
    ]

    operations = [
        migrations.RunPython(create_admin_pw_variable, reverse_code=migrations.RunPython.noop),
    ]
