# Generated by Django 5.1.5 on 2025-03-26 16:28

import django.db.models.deletion
from django.db import migrations, models


def create_default_organization(apps, schema_editor):
    """If there are existing Project, CentralServer, or TemplateVariable objects,
    create an Organization and link them to it.
    """
    org = None
    for model in ("Project", "CentralServer", "TemplateVariable"):
        model = apps.get_model("odk_publish", model)
        if model.objects.exists():
            if not org:
                org = apps.get_model("odk_publish", "Organization").objects.create(
                    name="Auto-created Organization", slug="auto-created-organization"
                )
            model.objects.update(organization=org)


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0009_formtemplate_template_url_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="centralserver",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="central_servers",
                to="odk_publish.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="odk_publish.organization",
            ),
        ),
        migrations.AddField(
            model_name="templatevariable",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_variables",
                to="odk_publish.organization",
            ),
        ),
        migrations.RunPython(create_default_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="centralserver",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="central_servers",
                to="odk_publish.organization",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="odk_publish.organization",
            ),
        ),
        migrations.AlterField(
            model_name="templatevariable",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_variables",
                to="odk_publish.organization",
            ),
        ),
    ]
