# Generated by Django 5.1.5 on 2025-03-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odk_publish", "0010_organization_centralserver_organization_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="templatevariable",
            name="unique_template_variable_name",
        ),
        migrations.AddConstraint(
            model_name="templatevariable",
            constraint=models.UniqueConstraint(
                fields=("name", "organization"), name="unique_template_variable_name"
            ),
        ),
    ]
