# Generated by Django 5.2.12 on 2026-03-25 16:06

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import apps.infisical.fields
import apps.mdm.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publish_mdm", "0014_organization_public_signup_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the device in the MDM.",
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, help_text="The serial number of the device.", max_length=255
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name or nickname of the device in the MDM.",
                        max_length=255,
                    ),
                ),
                (
                    "raw_mdm_device",
                    models.JSONField(
                        blank=True,
                        help_text="The raw JSON response from the MDM for this device.",
                        null=True,
                        verbose_name="Raw MDM Device",
                    ),
                ),
                (
                    "app_user_name",
                    models.CharField(
                        blank=True,
                        db_collation="case_insensitive",
                        help_text="Name of the app user (in the Publish MDM app) to assign to this device, if any.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Name can only contain alphanumeric characters, underscores, hyphens, and not more than one colon.",
                                regex="^(((:[a-zA-Z_]:?)?[-\\w]*)|([-\\w]+:[a-zA-Z_][-\\w]*))$",
                            )
                        ],
                    ),
                ),
            ],
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DeviceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="The ID of the device in the MDM.",
                        max_length=255,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name or nickname of the device in the MDM.", max_length=255
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(help_text="The serial number of the device.", max_length=255),
                ),
                (
                    "manufacturer",
                    models.CharField(help_text="The manufacturer of the device.", max_length=64),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True,
                        help_text="The version of the operating system.",
                        max_length=32,
                        null=True,
                        verbose_name="OS Version",
                    ),
                ),
                (
                    "battery_level",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="The current battery level of the device, as a percentage.",
                        null=True,
                    ),
                ),
                (
                    "enrollment_type",
                    models.CharField(
                        help_text="The type of enrollment for the device.", max_length=32
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        help_text="Last device synchronization with the MDM servers."
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="The last known latitude of the device.", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="The last known longitude of the device.", null=True
                    ),
                ),
                (
                    "raw_mdm_device",
                    models.JSONField(
                        help_text="The full JSON response from the MDM API for this device.",
                        verbose_name="Raw MDM Device",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(help_text="When the device snapshot was synced."),
                ),
                (
                    "mdm_device",
                    models.ForeignKey(
                        blank=True,
                        help_text="The device that this snapshot is for.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="mdm.device",
                        verbose_name="MDM Device",
                    ),
                ),
            ],
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="latest_snapshot",
            field=models.OneToOneField(
                blank=True,
                help_text="The latest snapshot of the device.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_device",
                to="mdm.devicesnapshot",
            ),
        ),
        migrations.CreateModel(
            name="DeviceSnapshotApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "package_name",
                    models.CharField(help_text="Complete name of the package.", max_length=255),
                ),
                ("app_name", models.CharField(help_text="Application name", max_length=255)),
                (
                    "version_code",
                    models.IntegerField(help_text="Current version code of the app on the device"),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Current version name of the app on the device", max_length=128
                    ),
                ),
                (
                    "device_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        to="mdm.devicesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FirmwareSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_identifier",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the device set via the MDM.",
                        max_length=255,
                        verbose_name="Device Identifier",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, help_text="The serial number of the device.", max_length=255
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, help_text="Firmware version", max_length=255),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the device snapshot was synced."
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="The full data sent by the device to Publish MDM.",
                        null=True,
                        verbose_name="Raw Device Data",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_snapshots",
                        to="mdm.device",
                    ),
                ),
            ],
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "mdm_group_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the group in the MDM.",
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="MDM Group ID",
                    ),
                ),
                (
                    "enroll_qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.mdm.models.enroll_qr_code_path,
                        verbose_name="enrollment QR code",
                    ),
                ),
                ("enroll_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("enroll_token_value", models.CharField(blank=True, max_length=30)),
                (
                    "default_app_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, newly enrolled devices are automatically assigned this app user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_fleet_set",
                        to="publish_mdm.appuser",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization that this fleet belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleets",
                        to="publish_mdm.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The project to deploy to this fleet of devices.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleets",
                        to="publish_mdm.project",
                    ),
                ),
            ],
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="fleet",
            field=models.ForeignKey(
                help_text="The fleet that the device is assigned to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="mdm.fleet",
            ),
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="The name of the policy.", max_length=255)),
                (
                    "policy_id",
                    models.CharField(
                        help_text="The ID of the policy in the MDM.",
                        max_length=255,
                        verbose_name="Policy ID",
                    ),
                ),
                (
                    "mdm",
                    models.CharField(
                        choices=[
                            ("TinyMDM", "TinyMDM"),
                            ("Android Enterprise", "Android Enterprise"),
                        ],
                        max_length=50,
                        verbose_name="MDM",
                    ),
                ),
                (
                    "odk_collect_package",
                    models.CharField(
                        default="org.odk.collect.android",
                        help_text="Package name for ODK Collect.",
                        max_length=255,
                    ),
                ),
                (
                    "odk_collect_device_id_template",
                    models.CharField(
                        blank=True,
                        default="${app_user_name}-${device_id}",
                        help_text="Template for the device_id field passed to ODK Collect's managed configuration. Supports built-in variables: $app_user_name, $device_id, $serial_number, $imei. Leave blank to omit device_id from the managed configuration.",
                        max_length=255,
                    ),
                ),
                (
                    "device_password_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASSWORD_QUALITY_UNSPECIFIED", "Unspecified"),
                            ("BIOMETRIC_WEAK", "Biometric weak"),
                            ("SOMETHING", "Something"),
                            ("NUMERIC", "Numeric"),
                            ("NUMERIC_COMPLEX", "Numeric complex"),
                            ("ALPHABETIC", "Alphabetic"),
                            ("ALPHANUMERIC", "Alphanumeric"),
                            ("COMPLEX", "Complex"),
                        ],
                        default="PASSWORD_QUALITY_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "device_password_min_length",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "device_password_require_unlock",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED", "Unspecified"),
                            ("USE_DEFAULT_DEVICE_TIMEOUT", "Use default device timeout"),
                            ("REQUIRE_EVERY_DAY", "Require every day"),
                        ],
                        default="REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "work_password_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASSWORD_QUALITY_UNSPECIFIED", "Unspecified"),
                            ("BIOMETRIC_WEAK", "Biometric weak"),
                            ("SOMETHING", "Something"),
                            ("NUMERIC", "Numeric"),
                            ("NUMERIC_COMPLEX", "Numeric complex"),
                            ("ALPHABETIC", "Alphabetic"),
                            ("ALPHANUMERIC", "Alphanumeric"),
                            ("COMPLEX", "Complex"),
                        ],
                        default="PASSWORD_QUALITY_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "work_password_min_length",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "work_password_require_unlock",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED", "Unspecified"),
                            ("USE_DEFAULT_DEVICE_TIMEOUT", "Use default device timeout"),
                            ("REQUIRE_EVERY_DAY", "Require every day"),
                        ],
                        default="REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "vpn_package_name",
                    models.CharField(
                        blank=True,
                        help_text="Package name for always-on VPN. Leave blank to disable.",
                        max_length=255,
                    ),
                ),
                (
                    "vpn_lockdown",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, all networking is blocked when VPN is not connected.",
                    ),
                ),
                (
                    "developer_settings",
                    models.CharField(
                        choices=[
                            ("DEVELOPER_SETTINGS_DISABLED", "Disallowed"),
                            ("DEVELOPER_SETTINGS_ALLOWED", "Allowed"),
                        ],
                        default="DEVELOPER_SETTINGS_DISABLED",
                        max_length=50,
                    ),
                ),
                (
                    "kiosk_power_button_actions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POWER_BUTTON_ACTIONS_UNSPECIFIED", "Unspecified"),
                            ("POWER_BUTTON_AVAILABLE", "Available"),
                            ("POWER_BUTTON_BLOCKED", "Blocked"),
                        ],
                        default="POWER_BUTTON_ACTIONS_UNSPECIFIED",
                        max_length=60,
                    ),
                ),
                (
                    "kiosk_system_error_warnings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SYSTEM_ERROR_WARNINGS_UNSPECIFIED", "Unspecified"),
                            ("ERROR_AND_WARNINGS_ENABLED", "Enabled"),
                            ("ERROR_AND_WARNINGS_MUTED", "Muted"),
                        ],
                        default="SYSTEM_ERROR_WARNINGS_UNSPECIFIED",
                        max_length=60,
                    ),
                ),
                (
                    "kiosk_system_navigation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SYSTEM_NAVIGATION_UNSPECIFIED", "Unspecified"),
                            ("NAVIGATION_ENABLED", "Enabled"),
                            ("NAVIGATION_DISABLED", "Disabled"),
                            ("HOME_BUTTON_ONLY", "Home button only"),
                        ],
                        default="SYSTEM_NAVIGATION_UNSPECIFIED",
                        max_length=60,
                    ),
                ),
                (
                    "kiosk_status_bar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STATUS_BAR_UNSPECIFIED", "Unspecified"),
                            (
                                "NOTIFICATIONS_AND_SYSTEM_INFO_ENABLED",
                                "Notifications and system info enabled",
                            ),
                            (
                                "NOTIFICATIONS_AND_SYSTEM_INFO_DISABLED",
                                "Notifications and system info disabled",
                            ),
                            ("SYSTEM_INFO_ONLY", "System info only"),
                        ],
                        default="STATUS_BAR_UNSPECIFIED",
                        max_length=60,
                    ),
                ),
                (
                    "kiosk_device_settings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEVICE_SETTINGS_UNSPECIFIED", "Unspecified"),
                            ("SETTINGS_ACCESS_ALLOWED", "Settings access allowed"),
                            ("SETTINGS_ACCESS_BLOCKED", "Settings access blocked"),
                        ],
                        default="DEVICE_SETTINGS_UNSPECIFIED",
                        max_length=60,
                    ),
                ),
                (
                    "kiosk_custom_launcher_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable the custom launcher when the device is in kiosk mode.",
                    ),
                ),
                (
                    "location_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOCATION_MODE_UNSPECIFIED", "Unspecified"),
                            ("HIGH_ACCURACY", "High accuracy (deprecated, Android 8 and below)"),
                            (
                                "SENSORS_ONLY",
                                "Sensors only / GPS (deprecated, Android 8 and below)",
                            ),
                            ("BATTERY_SAVING", "Battery saving (deprecated, Android 8 and below)"),
                            ("OFF", "Off (deprecated, Android 8 and below)"),
                            ("LOCATION_ENFORCED", "Enforced (Android 9+)"),
                            ("LOCATION_DISABLED", "Disabled (Android 9+)"),
                            ("LOCATION_USER_CHOICE", "User choice (Android 9+)"),
                        ],
                        default="LOCATION_MODE_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "connectivity_usb_data_access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USB_DATA_ACCESS_UNSPECIFIED", "Unspecified"),
                            ("ALLOW_USB_DATA_TRANSFER", "Allow USB data transfer"),
                            ("DISALLOW_USB_FILE_TRANSFER", "Disallow USB file transfer"),
                            ("DISALLOW_USB_DATA_TRANSFER", "Disallow all USB data transfer"),
                        ],
                        default="USB_DATA_ACCESS_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "connectivity_configure_wifi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFIGURE_WIFI_UNSPECIFIED", "Unspecified"),
                            ("ALLOW_CONFIGURING_WIFI", "Allow configuring Wi-Fi"),
                            ("DISALLOW_ADD_WIFI_CONFIG", "Disallow adding Wi-Fi networks"),
                            ("DISALLOW_CONFIGURING_WIFI", "Disallow configuring Wi-Fi"),
                        ],
                        default="CONFIGURE_WIFI_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "connectivity_tethering_settings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TETHERING_SETTINGS_UNSPECIFIED", "Unspecified"),
                            ("ALLOW_ALL_TETHERING", "Allow all tethering"),
                            ("DISALLOW_WIFI_TETHERING", "Disallow Wi-Fi tethering"),
                            ("DISALLOW_ALL_TETHERING", "Disallow all tethering"),
                        ],
                        default="TETHERING_SETTINGS_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "connectivity_wifi_direct_settings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WIFI_DIRECT_SETTINGS_UNSPECIFIED", "Unspecified"),
                            ("ALLOW_WIFI_DIRECT", "Allow Wi-Fi Direct"),
                            ("DISALLOW_WIFI_DIRECT", "Disallow Wi-Fi Direct"),
                        ],
                        default="WIFI_DIRECT_SETTINGS_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="publish_mdm.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "policies",
                "ordering": ("name",),
            },
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="fleet",
            name="policy",
            field=models.ForeignKey(
                help_text="The MDM policy to assign for this fleet of devices.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fleets",
                to="mdm.policy",
            ),
        ),
        migrations.CreateModel(
            name="PolicyApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                (
                    "install_type",
                    models.CharField(
                        choices=[
                            ("FORCE_INSTALLED", "Force installed"),
                            ("PREINSTALLED", "Pre-installed"),
                            ("AVAILABLE", "Available"),
                            ("KIOSK", "Kiosk"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="FORCE_INSTALLED",
                        max_length=20,
                    ),
                ),
                ("disabled", models.BooleanField(default=False)),
                (
                    "managed_configuration",
                    models.JSONField(
                        blank=True,
                        help_text="Managed configuration for this app (from Play Store iframe).",
                        null=True,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "default_permission_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERMISSION_POLICY_UNSPECIFIED", "Unspecified"),
                            ("PROMPT", "Prompt user"),
                            ("GRANT", "Grant automatically"),
                            ("DENY", "Deny automatically"),
                        ],
                        default="PERMISSION_POLICY_UNSPECIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="mdm.policy",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="PolicyVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=2048)),
                (
                    "value_encrypted",
                    apps.infisical.fields.EncryptedCharField(blank=True, null=True),
                ),
                ("is_encrypted", models.BooleanField(default=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[("policy", "Policy"), ("fleet", "Fleet")], max_length=10
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_variables",
                        to="mdm.fleet",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_variables",
                        to="mdm.policy",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="devicesnapshot",
            index=models.Index(fields=["last_sync"], name="mdm_devices_last_sy_8219e0_idx"),
        ),
        migrations.AddIndex(
            model_name="devicesnapshot",
            index=models.Index(fields=["synced_at"], name="mdm_devices_synced__c979ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="devicesnapshotapp",
            constraint=models.UniqueConstraint(
                fields=("device_snapshot", "package_name"),
                name="unique_device_snapshot_and_package",
            ),
        ),
        migrations.AddIndex(
            model_name="firmwaresnapshot",
            index=models.Index(fields=["synced_at"], name="mdm_firmwar_synced__9b7a41_idx"),
        ),
        migrations.AddConstraint(
            model_name="fleet",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_org_and_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyapplication",
            constraint=models.UniqueConstraint(
                fields=("policy", "package_name"), name="unique_policy_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyvariable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "policy")),
                fields=("key", "policy"),
                name="unique_policy_policy_variable",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyvariable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "fleet")),
                fields=("key", "fleet"),
                name="unique_fleet_policy_variable",
            ),
        ),
    ]
