# Generated by Django 5.1.5 on 2025-03-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="The ID of the device in the MDM.",
                        max_length=255,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name or nickname of the device in the MDM.", max_length=255
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(help_text="The serial number of the device.", max_length=255),
                ),
                (
                    "manufacturer",
                    models.CharField(help_text="The manufacturer of the device.", max_length=64),
                ),
                (
                    "os_version",
                    models.CharField(
                        help_text="The version of the operating system.",
                        max_length=32,
                        verbose_name="OS Version",
                    ),
                ),
                (
                    "battery_level",
                    models.SmallIntegerField(
                        help_text="The current battery level of the device, as a percentage."
                    ),
                ),
                (
                    "enrollment_type",
                    models.CharField(
                        help_text="The type of enrollment for the device.", max_length=32
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        help_text="Last device synchronization with TinyMDM servers."
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="The last known latitude of the device.", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="The last known longitude of the device.", null=True
                    ),
                ),
                (
                    "raw_mdm_device",
                    models.JSONField(
                        help_text="The full JSON response from the MDM API for this device.",
                        verbose_name="Raw MDM Device",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(help_text="When the device snapshot was synced."),
                ),
                (
                    "mdm_device",
                    models.ForeignKey(
                        blank=True,
                        help_text="The device that this snapshot is for.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="mdm.device",
                        verbose_name="MDM Device",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="latest_snapshot",
            field=models.OneToOneField(
                blank=True,
                help_text="The latest snapshot of the device.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_device",
                to="mdm.devicesnapshot",
            ),
        ),
        migrations.CreateModel(
            name="DeviceSnapshotApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "package_name",
                    models.CharField(help_text="Complete name of the package.", max_length=255),
                ),
                ("app_name", models.CharField(help_text="Application name", max_length=255)),
                (
                    "version_code",
                    models.IntegerField(help_text="Current version code of the app on the device"),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Current version name of the app on the device", max_length=128
                    ),
                ),
                (
                    "device_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        to="mdm.devicesnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="devicesnapshot",
            index=models.Index(fields=["last_sync"], name="mdm_devices_last_sy_8219e0_idx"),
        ),
        migrations.AddIndex(
            model_name="devicesnapshot",
            index=models.Index(fields=["synced_at"], name="mdm_devices_synced__c979ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="devicesnapshotapp",
            constraint=models.UniqueConstraint(
                fields=("device_snapshot", "package_name"),
                name="unique_device_snapshot_and_package",
            ),
        ),
    ]
