# Generated by Django 5.1.5 on 2025-04-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0002_devicesnapshot_device_latest_snapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmwareSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_identifier",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the device set via the MDM.",
                        max_length=255,
                        verbose_name="Device Identifier",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, help_text="The serial number of the device.", max_length=255
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, help_text="Firmware version", max_length=255),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the device snapshot was synced."
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="The full data sent by the device to Publish MDM.",
                        null=True,
                        verbose_name="Raw Device Data",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_snapshots",
                        to="mdm.device",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["synced_at"], name="mdm_firmwar_synced__9b7a41_idx")
                ],
            },
        ),
    ]
