# Generated by Django 5.2.1 on 2025-06-03 14:39

from django.db import migrations, models

import apps.mdm.models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0004_fleet_remove_device_unique_policy_and_device_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="enroll_qr_code",
            field=models.ImageField(
                null=True,
                upload_to=apps.mdm.models.enroll_qr_code_path,
                blank=True,
                verbose_name="enrollment QR code",
            ),
        ),
    ]
