# Generated by Django 5.2.2 on 2025-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0005_fleet_enroll_qr_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="policy",
            name="unique_default_policy",
        ),
        migrations.AddField(
            model_name="fleet",
            name="enroll_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="enroll_token_value",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="policy",
            name="mdm",
            field=models.CharField(
                choices=[("TinyMDM", "TinyMDM"), ("Android Enterprise", "Android Enterprise")],
                default="TinyMDM",
                max_length=50,
                verbose_name="MDM",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="devicesnapshot",
            name="battery_level",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The current battery level of the device, as a percentage.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default_policy", True)),
                fields=("default_policy", "mdm"),
                name="unique_default_policy",
                violation_error_message="A default policy already exists.",
            ),
        ),
        migrations.AlterField(
            model_name="devicesnapshot",
            name="last_sync",
            field=models.DateTimeField(
                help_text="Last device synchronization with the MDM servers."
            ),
        ),
        migrations.AlterField(
            model_name="devicesnapshot",
            name="os_version",
            field=models.CharField(
                blank=True,
                help_text="The version of the operating system.",
                max_length=32,
                null=True,
                verbose_name="OS Version",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="mdm_group_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the group in the MDM.",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="MDM Group ID",
            ),
        ),
    ]
