# Generated by Django 5.2.12 on 2026-03-21 16:52

import django.db.models.deletion
from django.db import migrations, models


def set_policy_organizations(apps, schema_editor):
    Policy = apps.get_model("mdm", "Policy")
    Organization = apps.get_model("publish_mdm", "Organization")
    first_org = Organization.objects.first()
    for policy in Policy.objects.filter(organization__isnull=True):
        fleet = policy.fleets.first()
        if fleet:
            policy.organization = fleet.organization
        elif first_org:
            policy.organization = first_org
        policy.save()


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0006_remove_policy_unique_default_policy_and_more"),
        ("publish_mdm", "0014_organization_public_signup_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="json_template",
        ),
        migrations.AddField(
            model_name="policy",
            name="developer_settings",
            field=models.CharField(
                choices=[
                    ("DEVELOPER_SETTINGS_DISABLED", "Disallowed"),
                    ("DEVELOPER_SETTINGS_ALLOWED", "Allowed"),
                ],
                default="DEVELOPER_SETTINGS_DISABLED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="device_password_min_length",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="device_password_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSWORD_QUALITY_UNSPECIFIED", "Unspecified"),
                    ("BIOMETRIC_WEAK", "Biometric weak"),
                    ("SOMETHING", "Something"),
                    ("NUMERIC", "Numeric"),
                    ("NUMERIC_COMPLEX", "Numeric complex"),
                    ("ALPHABETIC", "Alphabetic"),
                    ("ALPHANUMERIC", "Alphanumeric"),
                    ("COMPLEX", "Complex"),
                ],
                default="PASSWORD_QUALITY_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="device_password_require_unlock",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED", "Unspecified"),
                    ("USE_DEFAULT_DEVICE_TIMEOUT", "Use default device timeout"),
                    ("REQUIRE_EVERY_DAY", "Require every day"),
                ],
                default="REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_device_settings",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEVICE_SETTINGS_UNSPECIFIED", "Unspecified"),
                    ("SETTINGS_ACCESS_ALLOWED", "Settings access allowed"),
                    ("SETTINGS_ACCESS_BLOCKED", "Settings access blocked"),
                ],
                default="DEVICE_SETTINGS_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_power_button_actions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POWER_BUTTON_ACTIONS_UNSPECIFIED", "Unspecified"),
                    ("POWER_BUTTON_AVAILABLE", "Available"),
                    ("POWER_BUTTON_BLOCKED", "Blocked"),
                ],
                default="POWER_BUTTON_ACTIONS_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_status_bar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STATUS_BAR_UNSPECIFIED", "Unspecified"),
                    (
                        "NOTIFICATIONS_AND_SYSTEM_INFO_ENABLED",
                        "Notifications and system info enabled",
                    ),
                    (
                        "NOTIFICATIONS_AND_SYSTEM_INFO_DISABLED",
                        "Notifications and system info disabled",
                    ),
                    ("SYSTEM_INFO_ONLY", "System info only"),
                ],
                default="STATUS_BAR_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_system_error_warnings",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SYSTEM_ERROR_WARNINGS_UNSPECIFIED", "Unspecified"),
                    ("ERROR_AND_WARNINGS_ENABLED", "Enabled"),
                    ("ERROR_AND_WARNINGS_MUTED", "Muted"),
                ],
                default="SYSTEM_ERROR_WARNINGS_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_system_navigation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SYSTEM_NAVIGATION_UNSPECIFIED", "Unspecified"),
                    ("NAVIGATION_ENABLED", "Enabled"),
                    ("NAVIGATION_DISABLED", "Disabled"),
                    ("HOME_BUTTON_ONLY", "Home button only"),
                ],
                default="SYSTEM_NAVIGATION_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="odk_collect_package",
            field=models.CharField(
                default="org.odk.collect.android",
                help_text="Package name for ODK Collect.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="publish_mdm.organization",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="vpn_lockdown",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, all networking is blocked when VPN is not connected.",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="vpn_package_name",
            field=models.CharField(
                blank=True,
                help_text="Package name for always-on VPN. Leave blank to disable.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="work_password_min_length",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="work_password_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSWORD_QUALITY_UNSPECIFIED", "Unspecified"),
                    ("BIOMETRIC_WEAK", "Biometric weak"),
                    ("SOMETHING", "Something"),
                    ("NUMERIC", "Numeric"),
                    ("NUMERIC_COMPLEX", "Numeric complex"),
                    ("ALPHABETIC", "Alphabetic"),
                    ("ALPHANUMERIC", "Alphanumeric"),
                    ("COMPLEX", "Complex"),
                ],
                default="PASSWORD_QUALITY_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="work_password_require_unlock",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED", "Unspecified"),
                    ("USE_DEFAULT_DEVICE_TIMEOUT", "Use default device timeout"),
                    ("REQUIRE_EVERY_DAY", "Require every day"),
                ],
                default="REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PolicyApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                (
                    "install_type",
                    models.CharField(
                        choices=[
                            ("FORCE_INSTALLED", "Force installed"),
                            ("PREINSTALLED", "Pre-installed"),
                            ("AVAILABLE", "Available"),
                            ("KIOSK", "Kiosk"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="FORCE_INSTALLED",
                        max_length=20,
                    ),
                ),
                ("disabled", models.BooleanField(default=False)),
                (
                    "managed_configuration",
                    models.JSONField(
                        blank=True,
                        help_text="Managed configuration for this app (from Play Store iframe).",
                        null=True,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="mdm.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "package_name"), name="unique_policy_application"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=2048)),
                (
                    "scope",
                    models.CharField(
                        choices=[("org", "Organization"), ("fleet", "Fleet")], max_length=10
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_variables",
                        to="mdm.fleet",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_variables",
                        to="publish_mdm.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "org")),
                        fields=("key", "org"),
                        name="unique_org_policy_variable",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "fleet")),
                        fields=("key", "fleet"),
                        name="unique_fleet_policy_variable",
                    ),
                ],
            },
        ),
        migrations.RunPython(set_policy_organizations, migrations.RunPython.noop),
    ]
