# Generated by Django 5.2.12 on 2026-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0007_policy_editor_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"ordering": ("name",), "verbose_name_plural": "policies"},
        ),
        migrations.RemoveConstraint(
            model_name="policy",
            name="unique_default_policy",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="default_policy",
        ),
        migrations.AlterField(
            model_name="policyvariable",
            name="scope",
            field=models.CharField(choices=[("org", "Policy"), ("fleet", "Fleet")], max_length=10),
        ),
    ]
