# Generated by Django 5.2.2 on 2026-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0007_remove_policy_json_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="kiosk_custom_launcher_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_device_settings",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEVICE_SETTINGS_UNSPECIFIED", "Unspecified"),
                    ("SETTINGS_ACCESS_ALLOWED", "Settings access allowed"),
                    ("SETTINGS_ACCESS_BLOCKED", "Settings access blocked"),
                ],
                default="DEVICE_SETTINGS_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_power_button_actions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POWER_BUTTON_ACTIONS_UNSPECIFIED", "Unspecified"),
                    ("POWER_BUTTON_AVAILABLE", "Available"),
                    ("POWER_BUTTON_BLOCKED", "Blocked"),
                ],
                default="POWER_BUTTON_ACTIONS_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_status_bar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STATUS_BAR_UNSPECIFIED", "Unspecified"),
                    (
                        "NOTIFICATIONS_AND_SYSTEM_INFO_ENABLED",
                        "Notifications and system info enabled",
                    ),
                    (
                        "NOTIFICATIONS_AND_SYSTEM_INFO_DISABLED",
                        "Notifications and system info disabled",
                    ),
                    ("SYSTEM_INFO_ONLY", "System info only"),
                ],
                default="STATUS_BAR_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_system_error_warnings",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SYSTEM_ERROR_WARNINGS_UNSPECIFIED", "Unspecified"),
                    ("ERROR_AND_WARNINGS_ENABLED", "Enabled"),
                    ("ERROR_AND_WARNINGS_MUTED", "Muted"),
                ],
                default="SYSTEM_ERROR_WARNINGS_UNSPECIFIED",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="kiosk_system_navigation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SYSTEM_NAVIGATION_UNSPECIFIED", "Unspecified"),
                    ("NAVIGATION_ENABLED", "Enabled"),
                    ("NAVIGATION_DISABLED", "Disabled"),
                    ("HOME_BUTTON_ONLY", "Home button only"),
                ],
                default="SYSTEM_NAVIGATION_UNSPECIFIED",
                max_length=60,
            ),
        ),
    ]
