# Generated by Django 5.2.12 on 2026-03-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0007_policyapplication_policyvariable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="odk_collect_device_id_template",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Template for the device_id field passed to ODK Collect's managed configuration. Use {{ imei }} or {{ serial_number }} as placeholders. Leave blank to use the device's app-user username.",
                max_length=255,
            ),
        ),
    ]
