# Generated by Django 5.2.12 on 2026-03-24 19:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0007_fleet_default_app_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="device",
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="devicesnapshot",
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="firmwaresnapshot",
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="fleet",
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="policy",
            managers=[
                ("all_mdms", django.db.models.manager.Manager()),
            ],
        ),
    ]
