# Generated by Django 5.2.12 on 2026-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0008_policy_odk_collect_device_id_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="odk_collect_device_id_template",
            field=models.CharField(
                blank=True,
                default="{{ app_user_name }} - {{ device_id }}",
                help_text="Template for the device_id field passed to ODK Collect's managed configuration. Supports built-in variables: {{ app_user_name }}, {{ device_id }}, {{ serial_number }}, {{ imei }}. Leave blank to omit device_id from the managed configuration.",
                max_length=255,
            ),
        ),
    ]
