# Generated by Django 5.2.2 on 2026-03-21 14:45

import django.db.models.deletion
from django.db import migrations, models


def set_policy_organizations(apps, schema_editor):
    Policy = apps.get_model("mdm", "Policy")
    Organization = apps.get_model("publish_mdm", "Organization")
    first_org = Organization.objects.first()
    for policy in Policy.objects.filter(organization__isnull=True):
        fleet = policy.fleets.first()
        if fleet:
            policy.organization = fleet.organization
        elif first_org:
            policy.organization = first_org
        policy.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0008_policy_kiosk_custom_launcher_enabled_and_more"),
        ("publish_mdm", "0014_organization_public_signup_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="kiosk_custom_launcher_enabled",
        ),
        migrations.AddField(
            model_name="policy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="publish_mdm.organization",
            ),
        ),
        migrations.RunPython(set_policy_organizations, migrations.RunPython.noop),
    ]
