# Generated by Django 5.2.12 on 2026-03-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0009_policyapplication_policyvariable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="connectivity_configure_wifi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONFIGURE_WIFI_UNSPECIFIED", "Unspecified"),
                    ("ALLOW_CONFIGURING_WIFI", "Allow configuring Wi-Fi"),
                    ("DISALLOW_ADD_WIFI_CONFIG", "Disallow adding Wi-Fi networks"),
                    ("DISALLOW_CONFIGURING_WIFI", "Disallow configuring Wi-Fi"),
                ],
                default="CONFIGURE_WIFI_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="connectivity_tethering_settings",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TETHERING_SETTINGS_UNSPECIFIED", "Unspecified"),
                    ("ALLOW_ALL_TETHERING", "Allow all tethering"),
                    ("DISALLOW_WIFI_TETHERING", "Disallow Wi-Fi tethering"),
                    ("DISALLOW_ALL_TETHERING", "Disallow all tethering"),
                ],
                default="TETHERING_SETTINGS_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="connectivity_usb_data_access",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USB_DATA_ACCESS_UNSPECIFIED", "Unspecified"),
                    ("ALLOW_USB_DATA_TRANSFER", "Allow USB data transfer"),
                    ("DISALLOW_USB_FILE_TRANSFER", "Disallow USB file transfer"),
                    ("DISALLOW_USB_DATA_TRANSFER", "Disallow all USB data transfer"),
                ],
                default="USB_DATA_ACCESS_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="connectivity_wifi_direct_settings",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WIFI_DIRECT_SETTINGS_UNSPECIFIED", "Unspecified"),
                    ("ALLOW_WIFI_DIRECT", "Allow Wi-Fi Direct"),
                    ("DISALLOW_WIFI_DIRECT", "Disallow Wi-Fi Direct"),
                ],
                default="WIFI_DIRECT_SETTINGS_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="location_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOCATION_MODE_UNSPECIFIED", "Unspecified"),
                    ("HIGH_ACCURACY", "High accuracy (deprecated, Android 8 and below)"),
                    ("SENSORS_ONLY", "Sensors only / GPS (deprecated, Android 8 and below)"),
                    ("BATTERY_SAVING", "Battery saving (deprecated, Android 8 and below)"),
                    ("OFF", "Off (deprecated, Android 8 and below)"),
                    ("LOCATION_ENFORCED", "Enforced on (Android 9+)"),
                    ("LOCATION_DISABLED", "Disabled (Android 9+)"),
                    ("LOCATION_USER_CHOICE", "User choice (Android 9+)"),
                ],
                default="LOCATION_MODE_UNSPECIFIED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="policyapplication",
            name="default_permission_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERMISSION_POLICY_UNSPECIFIED", "Unspecified"),
                    ("PROMPT", "Prompt user"),
                    ("GRANT", "Grant automatically"),
                    ("DENY", "Deny automatically"),
                ],
                default="PERMISSION_POLICY_UNSPECIFIED",
                max_length=50,
            ),
        ),
    ]
