# Generated by Django 5.2.12 on 2026-04-08 23:20

import django.db.models.fields.json
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0009_feature_policy_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.fields.json.KeyTextTransform(
                        "brand",
                        django.db.models.fields.json.KeyTransform("hardwareInfo", "raw_mdm_device"),
                    ),
                    models.Value(""),
                    output_field=models.TextField(),
                ),
                help_text="The device brand extracted from raw MDM device data.",
                output_field=models.CharField(max_length=255),
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.fields.json.KeyTextTransform(
                        "model",
                        django.db.models.fields.json.KeyTransform("hardwareInfo", "raw_mdm_device"),
                    ),
                    models.Value(""),
                    output_field=models.TextField(),
                ),
                help_text="The device model extracted from raw MDM device data.",
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
