# Generated by Django 5.2.12 on 2026-04-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0010_remove_policy_mdm"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="device",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="devicesnapshot",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="firmwaresnapshot",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="fleet",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="policy",
            managers=[],
        ),
    ]
