# Generated by Django 5.2.12 on 2026-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0011_remove_policy_mdm_and_custom_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
            ),
        ),
    ]
