# Generated by Django 5.2.12 on 2026-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0012_device_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="status_report_application_reports_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether app reports are enabled.",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_common_criteria_mode_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether Common Criteria Mode reporting is enabled. This is supported only on company-owned devices.",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_device_settings_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether device settings reporting is enabled."
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_display_info_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether displays reporting is enabled. Report data is not available for personally owned devices with work profiles.",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_hardware_status_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether hardware status reporting is enabled. Report data is not available for personally owned devices with work profiles.",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_memory_info_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether memory event reporting is enabled."
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_network_info_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether network info reporting is enabled."
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_power_management_events_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether power management event reporting is enabled. Report data is not available for personally owned devices with work profiles.",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_software_info_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether software info reporting is enabled.",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status_report_system_properties_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether system properties reporting is enabled."
            ),
        ),
    ]
