# Generated by Django 5.2.13 on 2026-04-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.mdm.models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0013_status_reporting_settings"),
        ("publish_mdm", "0018_alter_organization_mdm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="A human-readable label for this token.",
                        max_length=255,
                    ),
                ),
                (
                    "token_value",
                    models.CharField(
                        blank=True,
                        help_text="The enrollment token value returned by the MDM API.",
                        max_length=500,
                    ),
                ),
                (
                    "token_resource_name",
                    models.CharField(
                        blank=True,
                        help_text="The AMAPI resource name for this token (used for deletion).",
                        max_length=255,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.mdm.models.enrollment_token_qr_code_path,
                        verbose_name="enrollment QR code",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this enrollment token expires.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this enrollment token was revoked. Null means not revoked.",
                        null=True,
                    ),
                ),
                (
                    "allow_personal_usage",
                    models.CharField(
                        choices=[
                            (
                                "ALLOW_PERSONAL_USAGE_UNSPECIFIED",
                                "Personal usage restriction is not specified",
                            ),
                            ("PERSONAL_USAGE_ALLOWED", "Personal usage is allowed"),
                            ("PERSONAL_USAGE_DISALLOWED", "Personal usage is disallowed"),
                            (
                                "PERSONAL_USAGE_DISALLOWED_USERLESS",
                                "Device is not associated with a single user, and thus both personal usage and corporate identity authentication are not expected.",
                            ),
                        ],
                        default="ALLOW_PERSONAL_USAGE_UNSPECIFIED",
                        help_text="Whether personal usage is allowed on enrolled devices.",
                        max_length=60,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this token.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_enrollment_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        help_text="The fleet that devices enrolling with this token will be assigned to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_tokens",
                        to="mdm.fleet",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Denormalized organization FK for easy tenant scoping.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_tokens",
                        to="publish_mdm.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
