# Generated by Django 5.2.13 on 2026-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0013_status_reporting_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firebase Cloud Messaging registration token for the firmware app.",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="screen_stream_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Per-device secret used by the firmware app to authenticate its screen-share WebSocket connection.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=~models.Q(screen_stream_token=""),
                fields=["screen_stream_token"],
                name="unique_device_screen_stream_token",
            ),
        ),
    ]
