# Generated by Django 5.2.13 on 2026-05-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0014_device_screen_sharing"),
        ("mdm", "0014_enrollmenttoken"),
    ]

    operations = []
