# Generated by Django 5.2.13 on 2026-05-13 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0015_device_screen_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when this device record was first created.",
            ),
            preserve_default=False,
        ),
    ]
