from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "publish_mdm"
urlpatterns = [
    path(
        "o/<slug:organization_slug>/",
        login_required(TemplateView.as_view(template_name="home.html")),
        name="organization-home",
    ),
    path(
        "o/<slug:organization_slug>/servers/sync/",
        views.server_sync,
        name="server-sync",
    ),
    path(
        "o/<slug:organization_slug>/servers/sync/projects/",
        views.server_sync_projects,
        name="server-sync-projects",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/edit/",
        views.change_project,
        name="edit-project",
    ),
    path(
        "o/<slug:organization_slug>/add-project/",
        views.change_project,
        name="add-project",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/app-users/",
        views.app_user_list,
        name="app-user-list",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/app-users/<int:app_user_pk>/",
        views.app_user_detail,
        name="app-user-detail",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/app-users/generate-qr-codes/",
        views.app_user_generate_qr_codes,
        name="app-users-generate-qr-codes",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/app-users/export/",
        views.app_user_export,
        name="app-users-export",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/app-users/import/",
        views.app_user_import,
        name="app-users-import",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/form-templates/",
        views.form_template_list,
        name="form-template-list",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/form-templates/<int:form_template_id>/",
        views.form_template_detail,
        name="form-template-detail",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/form-templates/<int:form_template_id>/publish/",
        views.form_template_publish,
        name="form-template-publish",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/form-templates/add/",
        views.change_form_template,
        name="add-form-template",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/form-templates/<int:form_template_id>/edit/",
        views.change_form_template,
        name="edit-form-template",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/app-users/add/",
        views.change_app_user,
        name="add-app-user",
    ),
    path(
        "o/<slug:organization_slug>/<int:odk_project_pk>/app-users/<int:app_user_id>/edit/",
        views.change_app_user,
        name="edit-app-user",
    ),
    path("create-organization/", views.create_organization, name="create-organization"),
    path(
        "o/<slug:organization_slug>/send-invite/",
        views.SendOrganizationInvite.as_view(),
        name="send-invite",
    ),
    path(
        "o/<slug:organization_slug>/request-invite/",
        views.RequestOrganizationInvite.as_view(),
        name="request-invite",
    ),
    path(
        "o/<slug:organization_slug>/users/",
        views.organization_users_list,
        name="organization-users-list",
    ),
    path(
        "o/<slug:organization_slug>/template-variables/",
        views.organization_template_variables,
        name="organization-template-variables",
    ),
    path(
        "o/<slug:organization_slug>/central-servers/",
        views.central_servers_list,
        name="central-servers-list",
    ),
    path(
        "o/<slug:organization_slug>/central-servers/<int:central_server_id>/",
        views.change_central_server,
        name="edit-central-server",
    ),
    path(
        "o/<slug:organization_slug>/central-servers/add/",
        views.change_central_server,
        name="add-central-server",
    ),
    path(
        "o/<slug:organization_slug>/devices/",
        views.devices_list,
        name="devices-list",
    ),
    path(
        "o/<slug:organization_slug>/fleets/",
        views.fleets_list,
        name="fleets-list",
    ),
    path(
        "o/<slug:organization_slug>/fleet/<int:fleet_id>/",
        views.edit_fleet,
        name="edit-fleet",
    ),
    path(
        "o/<slug:organization_slug>/fleet/add/",
        views.add_fleet,
        name="add-fleet",
    ),
    path(
        "o/<slug:organization_slug>/fleet-qr-code/",
        views.fleet_qr_code,
        name="fleet-qr-code",
    ),
    path(
        "o/<slug:organization_slug>/add-byod-device/",
        views.add_byod_device,
        name="add-byod-device",
    ),
]
